version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "development"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
